### PR TITLE
fix #1 and add comments

### LINKED ISSUE #1: travis is still looking for 9il/cblas
hence the dead link in the readme

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by 9il** [comment]
@John-Colvin, I have added blank comments to improve docs at http://ddocs.org/cblas/~master/cblas.html .

**Comment by John-Colvin** [comment]
We should probably agree on how we are going to work w.r.t. making changes, pull requests etc. I've been just pushing to master everywhere in order to move quickly, but that can't go on forever.

btw, there is a website now, I'm going through all the repositories adding pages. http://dlangscience.github.io   In particular see dstats, which has the docs included. I'm not whether it's better to keep them in-house or to rely on ddocs.org

**Comment by John-Colvin** [comment]
I've created an organisations members' Gitter room for general discussion, you should have got the invite.

**Comment by 9il** [comment]
Thanks!

**Pull request merged**
